### ISSUE TITLE
添加坐标出现问题 1.16

### ISSUE THREAD

**Issue by W-Kazdel** [Da-Dog/MCDR-Warp#4]
[MCDR] [00:16:15] [PT0-on_info@warpR/ERROR]: Error calling on_info in plugin warpR
Traceback (most recent call last):
  File "F:\1.16.2\1.16.2\utils\plugin_thread.py", line 41, in run
    task_data.func(*task_data.args)
  File "plugins\warpR.py", line 66, in on_info
    warp_add(args, server, info)
  File "plugins\warpR.py", line 208, in warp_add
    warp_list[args[2]] = [dim, x, y, z]
TypeError: list indices must be integers or slices, not str

**Comment by Da-Dog** [comment]
1.16.2 刚测试了，没法重现这个Bug，你可以尝试重新安装插件

**Comment by Da-Dog** [comment]
Reopen this issue if you have further question
